### ISSUE TITLE
Memory Leak/Hanging when scrolling if auto spell check is active

### ISSUE THREAD

**Issue by khamseen** [Predelnik/DSpellCheck#159] opened 2018-11-28 17:33 UTC
I'm finding that when scrolling through certain files, not huge just around 2k lines, that if I have auto spell check enabled Notepad++ becomes unresponsive and when I check task manager it starts consuming huge amounts of RAM. I've seen it use up to 13GB before force I've force closed the application. 

I'm running NPP 7.5.9 64bit with DSpellCheck 1.4.8 64bit plugin.

It happens to me every single time with server logs from a gaming server I run. I have to continually disable the auto spell checker if I want to scroll through the log files without it locking up.

**Comment by Predelnik** [comment] 2018-11-29 17:07
Thank you very much for providing the file!
Can reproduce the issue and endless loop allocating memory is pretty bad issue to have, will try to fix it asap.

**Comment by Predelnik** [comment] 2018-11-29 20:01
Looks like these file contains invalid utf-8 characters for some reason. But anyway it's poor behavior from plugin to hang in this case.
Here's a version with the fix I've made:
https://ci.appveyor.com/api/buildjobs/ghwf9jcho13cxbr4/artifacts/DSpellCheck.dll
Can you please check that it resolves the issue on your side?

**Comment by khamseen** [comment] 2018-11-29 20:33
Thanks for the quick update there man! I'll be honest, I'm not sure why that particular mod outputs non utf-8 characters but I haven't really questioned it haha.
I've tested your fix and it seems to be working, no more hanging when scrolling through the log files and memory usage is stable again!

**Comment by Predelnik** [comment] 2018-12-16 19:51
1.4.9 version containing the fix should be available through plugin manager now, so closing this issue.

**Closed by Predelnik** 2018-12-16 19:51 UTC
