### ISSUE TITLE
Exception: vector<T> is too long - new cause

### ISSUE THREAD

**Issue by aevojoey** [Predelnik/DSpellCheck#151] opened 2018-10-23 19:52 UTC
This seems to be the same error as [https://github.com/Predelnik/DSpellCheck/issues/139] that was closed on July 22 but with a different way of getting it.

### Description of the Issue

Since updating to notepad++ version 7.5.9, I have been getting the "Exception: vector<T> is too long" error. It only occurs when a collapsible line is collapsed and visible on the screen and you try to scroll horizontally. If a collapsed line is not on the screen, there is no error.
I removed the DSpellCheck v1.4.6 plugin and the error stopped.

### Steps to Reproduce the Issue

1. Open a file with collapsible lines (html, js, php, etc.)
2. Find a line that is longer than the width of the screen with a collapsible line on the screen
3. Do not collapse the line and scroll horizontally (with home/end, arrows or scroll bar) -> no errors
4. Collapse a line on the screen and try scrolling horizontally again -> Exception.
5. Scroll vertically so that the collapsed line is no longer visible and try scrolling -> no error

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll ComparePlugin.dll HTMLTag_unicode.dll ImgTag.dll JSLintNpp.dll JSMinNPP.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by Predelnik** [comment] 2018-10-25 19:52
Thank you very much for describing the issue so thoroughly! Since this is a serious problem I will try to release a version with the fix very soon. 

Meanwhile could you check if the version of the plugin from the link below fixes the issue for you if it wouldn't be too much trouble?
https://ci.appveyor.com/api/buildjobs/s4mc8o0q6wum0e2i/artifacts/DSpellCheck.dll

**Comment by guy038** [comment] 2018-10-27 20:11
Hi, **Predelnik**,

Ah, yes ! **aevojoey** is quite **right** about it ! I had this **same** issue, too and I verified that it happens also, with versions **`v1.4.5`** and version **`1.4.4`** with the fix of the bug **`#139`** :-((

But again, **Sergey**, the **fix** of the **`v1.4.6`** that you propose, in case of **folded** lines, must had been compiled **without** the **XP** support ( **same** issue as in my **reply**, relative to issue **`139`** ) !

Many **thanks** for investigating ;-))

guy038

**Comment by Predelnik** [comment] 2018-10-28 08:07
> must had been compiled without the XP support 

Yeah it was a bug in CI script. This version should b ewith winxp support:
https://ci.appveyor.com/api/buildjobs/imtsoq6ll9yn8qfe/artifacts/DSpellCheck.dll

**Comment by guy038** [comment] 2018-10-28 22:49
Hello, **Predelnik**,

Ah, I'm really **sorry**, but I always get an **error** ! This time, the message, in French, said :

**`The application or DLL C:\WINDOWS\System32\MSVCP140.dll is not a valid Windows image`**

Oddly, I don't have any **dll**, named **`MSVPC140.dll`**, on my system ! I, then, tried to download, successively, **several** versions of that **dll**, from various sites. But, either I got the **same** message or I had a message that the **`VCRUNTIME140.dll`** was missing :-((

And after download of the **unique** version of **`VCRUNTIME140.dll`** ( among 4 **DLL** sites ! ), install on **`C:\windows\system32`** and a laptop **reboot**, I **still** got errors :-((

What am I doing **wrong** ?

Cheers,

guy038

**Comment by Predelnik** [comment] 2018-10-29 09:17
Yeah it should not be the case, seems to be another problem on my (appveyor) side. This one is a little bit more confusing as it can be seen from logs that it correctly compiles with `/MT` option for C runtime.

I will look into it.

**Comment by Predelnik** [comment] 2018-10-29 21:13
Ok good news is that I've discovered the cause of the issue after spending some time. It was due to bad typo in CMakeLists.txt resulting in my Release build not being correct. And since I deploy 'Release with Debug Info' build most of the time, it was not affecting me that much.

Here is version which should work (sorry for that many iterations):
https://ci.appveyor.com/api/buildjobs/m8jk80d0t0tm5ixv/artifacts/DSpellCheck.dll

**Comment by guy038** [comment] 2018-10-30 19:21
Hi, **Predelnik**,

This time , it's the **right** one, **Sergey** ! Everything is **OK**, with your **last** version, on my **Win XP** configuration ;-))

Many **thanks** for checking your code and fixing that issue !

Cheers,

guy038

**Comment by trackvsb** [comment] 2018-11-13 15:22
I have the same issue when choosing language ASP to view a copy/pasted text. Switching to other languages does not throw this error. 
Windows 7 Professional on desktop, Notepad++ 7.5.4 64 bit.

**Comment by Predelnik** [comment] 2018-11-13 17:08
@trackvsb 
Just to make sure - is problem still reproducible with the version from the link below? 
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.7

**Comment by trackvsb** [comment] 2018-11-14 20:45
The problem disappeared after I updated from 1.4.6 to 1.4.7. Thanks for the fast response!

**Comment by Predelnik** [comment] 2018-11-20 21:49
This case should be fixed by 1.4.8 currently available through plugin manager. Please report any other cases of this error, thanks!

**Closed by Predelnik** 2018-11-20 21:49 UTC

**Comment by laconeo** [comment] 2019-03-04 10:38
i get ---------------------------
Plugin Exception
---------------------------
An exception occurred due to plugin: DSpellCheck.dll
Exception reason: vector<T> too long
---------------------------
Aceptar   
---------------------------

every time when i make scroll i get these error

**Comment by Predelnik** [comment] 2019-03-04 12:04
Hi @laconeo 
First of all which version of the plugin are you using? Can you try the latest version first, you can find here: https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.10

If it still does not fix the issue it would be really great if you would provide an example of the file where you get this error.

**Comment by laconeo** [comment] 2019-03-04 13:19
i was using 1.4.6 i have updated to the last version and problem solucionated! thanks!

**Comment by piitr64** [comment] 2019-12-30 14:38
Hi @Predelnik 
After automatically upgrade N++ (v.7.8.2) stay DSpellCheck.dll in v. 1.4.6 - Why?
After manually download and replace v.1.4.10 error is removal.
Thanks for info.

**Comment by Predelnik** [comment] 2019-12-31 08:12
@piitr64 Through `Plugins->Plugins Admin` version 1.4.15 is available, I don't know if plugins are updated automatically after updating N++ though but that's beyond my control.
