### ISSUE TITLE
notepad+ crash

### ISSUE THREAD

**Issue by DaveXuYuanfu** [Predelnik/DSpellCheck#218] opened 2020-06-19 11:55 UTC
version:1.4.16.0

steps：
1.open plugin
![image](https://user-images.githubusercontent.com/24265286/85129961-9d148f00-b266-11ea-9510-6b5ab84590fb.png)

2.download English language
![image](https://user-images.githubusercontent.com/24265286/85129997-ac93d800-b266-11ea-8fb2-85d0544af847.png)

3.progress bar still 0，then crash
![image](https://user-images.githubusercontent.com/24265286/85130037-c03f3e80-b266-11ea-9c76-28de6bab27bd.png)

so i can't use it,please check it,thanks

**Comment by xixidodo** [comment] 2020-07-01 07:28
I managed to mannually download under the guide as below, hope it helps

https://github.com/Predelnik/DSpellCheck/issues/62#issuecomment-349521662

**Comment by Predelnik** [comment] 2020-07-05 14:52
Would it be possible to create dump of Notepad++ memory during crash and send it to me via e-mail (or other means)?
![image](https://user-images.githubusercontent.com/2133957/86535299-08f22b00-bee8-11ea-8d4a-7313a034dda8.png)
This would help me greatly to resolve the issue.

With my configuration I can't reproduce it. Do you use any options for proxy btw?

**Comment by Predelnik** [comment] 2020-08-12 18:37
There is also a chance that this is the same issue as
https://github.com/Predelnik/DSpellCheck/issues/205

If that's the case then it would be nice to recheck it with version [1.4.16](https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.16)

**Comment by Predelnik** [comment] 2020-10-16 04:42
It is highly likely that crash was fixed in 1.4.18, more detailed errors are planned for the future version

**Closed by Predelnik** 2020-10-16 04:42 UTC
