### ISSUE TITLE
Delimiters list has character encoding issues and gets corrupted

### ISSUE THREAD

**Issue by Dwedit** [Predelnik/DSpellCheck#79] opened 2016-06-16 14:20 UTC
Sometimes, when I add Unicode characters to the delimiters list and run Notepad++ again at a later date, I see the delimiters list now has substituted characters in there, some delimiters have turned into ?.  I even saw a plain lowercase 'c' in there, which greatly disrupted spell checking.

**Comment by Predelnik** [comment] 2017-10-29 13:59
Quite late answer, but it will be fixed in 1.3.3. See #108

**Comment by Predelnik** [comment] 2017-12-09 20:56
The issue is closed since version 1.3.3 is avilable through plugin manager.

**Closed by Predelnik** 2017-12-09 20:56 UTC
