### ISSUE TITLE
Listing dictionary files in FTP directory fails

### ISSUE THREAD

**Issue by robertluwang** [Predelnik/DSpellCheck#111] opened 2017-11-17 02:57 UTC
I installed DSpellChecker for latest npp 7.5.1 x64, the hunspell library and Dictionaries still missing.

For my understanding, hunspell should be part of DSpellChecker plugin:
Hunspell library (Dictionaries by default should be placed to %Plugin Config Dir%\Hunspell)

But I cannot find Hunspell folder under npp\plugins\Config, also Dictionaries download got error:
ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/
Status:Cannot list directory files

I can access to ftp server from browser manually.

anyway I made it work in this way, manually places missing hunspell.dll, en_US.aff, en_US.dic to npp\plugins\Config\Hunspell, then it works fine now.

[https://github.com/robertluwang/npp-setting/blob/master/npp-spell-checker.md](https://github.com/robertluwang/npp-setting/blob/master/npp-spell-checker.md)

Hope you can find out issue and fix it.

In the last, I would like to thank you guys really great work to add such elegant tool in npp.

All the best,

Robert

**Comment by Predelnik** [comment] 2017-11-17 07:28
So first of all Hunspell.dll is most definetily not needed, it's linked into plugin statically. Hunspell doesn't have any official installation as far as I remember, and even if I ended up compiling it to separate dll that wouldn't help that much because its API isn't stable.

As for "Can't list directory files" problem, it needs investigation, can you tell me which version of plugin and which windows version do you have?

**Comment by robertluwang** [comment] 2017-11-17 13:55
@Predelnik thanks for your quick verification on hunspell.dll, it is true when I removed it the spell checker still working well, cool.

I used DSpellChecker plugin is v1.3.2.0 with npp 7.5.1 x64 on Windows7 ent x64.

BR/
Robert

**Comment by Predelnik** [comment] 2017-11-18 07:43
So honestly I have no idea what can cause this for now, I do remember having some trouble with FTP in the past on specific machines/systems though.
Can you try running Notepad++ from admin and see if it changes anything?
The other thing we could try is that I would add some sort of log of anything what is going on with FTP connection and you will run it on your machine. Is it possible?

**Comment by robertluwang** [comment] 2017-11-18 19:02
@Predelnik It is working when I run notepad++ in office by adding proxy host and port, however not working at home without proxy needed, it is strange but at least it seems related to ftp proxy.

**Comment by Predelnik** [comment] 2017-11-21 06:11
If it won't bother you could you please download this version:
https://drive.google.com/uc?export=download&id=0B_fsSThBdq2mOE5oN3poczRhX3c
Go to DSpellCheck Settings, press right click anywhere, select "Enable Debug Logging":
![image](https://user-images.githubusercontent.com/2133957/33057400-d47d5a1e-ce9b-11e7-8dc6-21d074df9ce7.png)
Then go to download dictionaries, get the error message.
Get back to settings dialog, press right click and select "Open Debug Log" and post its contents in here.
This should help me to find the cause of the problem.

**Comment by robertluwang** [comment] 2017-11-22 14:45
Here is debug log:
```
Got reply 220 with value:
220-                Welcome to the ftp.snt.utwente.nl archive.
220-This service is provided to you by:
220-                                   
220-Studenten Net Twente (SNT)    http://www.snt.utwente.nl/ 
220-the University of Twente      http://www.utwente.nl/  
220-
220-This system may be used 24 hours a day, 7 days a week.
220-
220-All transfers are logged with your hostname and email address.
220-If you don't like this policy, disconnect now!
220-
220-We are available on:
220-  http://ftp.snt.utwente.nl/
220-   ftp://ftp.snt.utwente.nl/
220- rsync://ftp.snt.utwente.nl/
220-
220-
220-Sponsors:
220-Quarantainenet BV         http://www.quarantainenet.nl
220-Byte                      http://www.byte.nl
220-Murphy Software B.V.      http://www.murphy.nl
220-Virtu Secure Webservices  http://www.virtu.nl
220-Utwente Faculty of TNW    http://www.tnw.utwente.nl
220-Sjoerd van Groning
220-Daan van de Linde
220-
220-
220-DISCLAIMER: Neither University of Twente nor SNT are liable for any use, 
220-storage or transmission of any files stored on this archive. Since 
220-much of our archive is mirrored from other servers, we can not check 
220-all files for virusinfections.  Please proceed with caution.
220-
220-If you have any problems or comments about this archive, please send
220-them via e-mail to ftpcom_at_snt.utwente.nl. Please also let us know 
220-if there is something we don't have that you think we should!
220-
220-
220-
220 
Command USER with args: anonymous
Got reply 331 with value:
331 Please specify the password.
Command PASS with args: anonymous@user.com
Got reply 230 with value:
230 Login successful.
Command CWD with args: /
Got reply 250 with value:
250 Directory successfully changed.
Command TYPE with args: A
Got reply 200 with value:
200 Switching to ASCII mode.
Command PASV with args: 
Got reply 227 with value:
227 Entering Passive Mode (130,89,149,20,245,127).
Fatal error Connect error 0x0000274c in file D:\devel\DSpellCheck\FtpClient\FTPClient.cpp on line 1042
```

Thanks.

BR/
Robert

**Comment by Predelnik** [comment] 2017-11-22 18:40
Thank you very much for this!
So as I found from quick googling it seems like the problem is that FTP passive connection may not always be established based on NAT/firewall settings in the environment which you have. I removed `passive` flag from FTP operations in the version I provide below. It would be really great if you could check it out.
https://drive.google.com/uc?export=download&id=1lp4wAhG5Hzut1Ly7wL73TUgN8yZEitD3

Since it causes such troubles and does not seem to provide much benefit I may remove it in general in next version and add only as option if it is required.

**Comment by robertluwang** [comment] 2017-11-22 19:27
Still failed, here is error details:
```
Command USER with args: anonymous
Got reply 331 with value:
331 Please specify the password.
Command PASS with args: anonymous@user.com
Got reply 230 with value:
230 Login successful.
Command CWD with args: /
Got reply 250 with value:
250 Directory successfully changed.
Command TYPE with args: A
Got reply 200 with value:
200 Switching to ASCII mode.
Command PORT with args: 192,168,1,100,206,184
Got reply 200 with value:
200 PORT command successful. Consider using PASV.
Command LIST with args: pub/software/openoffice/contrib/dictionaries/
Fatal error Receive timeout error in file D:\devel\DSpellCheck\FtpClient\FTPClient.cpp on line 1274
```

Thanks.

BR/
Robert

**Comment by Predelnik** [comment] 2017-11-23 18:49
Thank you very much for such a quick response.
Here's another thing I would like to try, this version has increased timeout for ftp connection. Looks like my timeout was set pretty low, so maybe that's the case. I also kept passive flag removed just in case.
https://drive.google.com/uc?export=download&id=1jpQwMxPDOUryoEpjV2brfv2JALDmdYux

**Comment by robertluwang** [comment] 2017-11-24 15:30
@Predelnik good news this version is working well! 
Thanks very much for your great help, finally fix this bug.

BR/
Robert
![spellchecker-hunspell-increase-timeout-ok](https://user-images.githubusercontent.com/20781253/33216579-64098c26-d102-11e7-9ff5-220cc3115d3d.jpg)

**Comment by Predelnik** [comment] 2017-11-24 20:03
Thank you very much for cooperation! Adding this fix to 1.3.3 and future versions.

**Comment by Predelnik** [comment] 2017-12-09 20:54
I'm closing this since the changes were added to version 1.3.3 which is available through plugin manager.

**Comment by MrX-at-GitHub** [comment] 2018-01-29 23:08
Hello,

Still failing in DSpellCheck.dll v1.3.5

OS: Windows 8.1 x64
notepad++ 7.5.4

**Comment by Predelnik** [comment] 2018-01-30 07:53
@MrX-at-GitHub 
Can you try 1.4.0 beta please:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.0-beta1
It was actually a mistake to disable passive FTP mode so I restored it as an option (turned on by default). It actually led to the same error on one of my systems too.

**Comment by MrX-at-GitHub** [comment] 2018-01-30 09:47
Thanks for your kind reply but it didn't work. Same issue.

**Comment by MrX-at-GitHub** [comment] 2018-01-30 13:00
ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/
and
ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/contrib/dictionaries/
yes.

ftp://gd.tuwien.ac.at/office/openoffice/contrib/dictionaries/
no.

Log:
`Got reply 220 with value:
220-                Welcome to the ftp.snt.utwente.nl archive.

220-This service is provided to you by:

220-                                   

220-Studenten Net Twente (SNT)    http://www.snt.utwente.nl/ 

220-the University of Twente      http://www.utwente.nl/  

220-

220-This system may be used 24 hours a day, 7 days a week.

220-

220-All transfers are logged with your hostname and email address.

220-If you don't like this policy, disconnect now!

220-

220-We are available on:

220-  http://ftp.snt.utwente.nl/

220-   ftp://ftp.snt.utwente.nl/

220- rsync://ftp.snt.utwente.nl/

220-

220-

220-Sponsors:

220-Quarantainenet BV         http://www.quarantainenet.nl

220-Byte                      http://www.byte.nl

220-Murphy Software B.V.      http://www.murphy.nl

220-Virtu Secure Webservices  http://www.virtu.nl

220-Utwente Faculty of TNW    http://www.tnw.utwente.nl

220-Sjoerd van Groning

220-Daan van de Linde

220-

220-

220-DISCLAIMER: Neither University of Twente nor SNT are liable for any use, 

220-storage or transmission of any files stored on this archive. Since 

220-much of our archive is mirrored from other servers, we can not check 

220-all files for virusinfections.  Please proceed with caution.

220-

220-If you have any problems or comments about this archive, please send

220-them via e-mail to ftpcom_at_snt.utwente.nl. Please also let us know 

220-if there is something we don't have that you think we should!

220-

220-

220-

220 
Command USER with args: anonymous
Got reply 331 with value:
331 Please specify the password.
Command PASS with args: anonymous@user.com
Got reply 230 with value:
230 Login successful.
Command CWD with args: /
Got reply 250 with value:
250 Directory successfully changed.
Command TYPE with args: A
Got reply 200 with value:
200 Switching to ASCII mode.
Command PORT with args: 192,168,0,150,212,17
Got reply 500 with value:
500 Illegal PORT command.
Got reply 220 with value:
220 Welcome to SunSITE CEUR
Command USER with args: anonymous
Got reply 331 with value:
331 Please specify the password.
Command PASS with args: anonymous@user.com
Got reply 230 with value:
230 Login successful.
Command CWD with args: /
Got reply 250 with value:
250 Directory successfully changed.
Command TYPE with args: A
Got reply 200 with value:
200 Switching to ASCII mode.
Command PORT with args: 192,168,0,150,212,19
Fatal error Receive error 0x00002746 in file D:\devel\DSpellCheck\deps\FtpClient\FTPClient.cpp on line 1274
Fatal error Connect error 0x0000274c in file D:\devel\DSpellCheck\deps\FtpClient\FTPClient.cpp on line 396
`

**Comment by Predelnik** [comment] 2018-01-30 19:46
So it looks like it still tries active mode according to

> 500 Illegal PORT command.

and missing `PASV` command. I found one typo in my code, not sure if it's relevant but I was going to release new beta version anyway. Can you please check this version and also check if "Use Passive Mode..." checkbox is ticked off in `Connection Settings` dialog if not turn it on.
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.0-beta2

**Comment by MrX-at-GitHub** [comment] 2018-01-30 20:30
This beta correctly populates the list from:
ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/
ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/contrib/dictionaries/

Connection cannot be established, **but remember this server is currently offline**:
ftp://gd.tuwien.ac.at/office/openoffice/contrib/dictionaries/

Downloaded my wanted dictionary and installed successfully. Thanks a lot.

Are you going to release a final version today and digitally signed (important to me)?

**Comment by Predelnik** [comment] 2018-01-30 20:55
I think not today but in a couple of days if everything is fine.
Have no experience with signing, but found this issue about signing Notepad++ which has plenty of details:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/49
I could do that possibly but can't promise that it could be done with this release sadly.

**Comment by MrX-at-GitHub** [comment] 2018-01-30 21:03
Fine. Forget the signing thing, notepad++ dev signs it for you.

If is it not too much to ask, could please post the download link here for the final version when available?
This way I will be able to grab it asap.

TIA

**Comment by Predelnik** [comment] 2018-01-30 21:09
> If is it not too much to ask, could please post the download link here for the final version when available?
This way I will be able to grab it asap.

Alright

**Comment by Predelnik** [comment] 2018-02-17 20:03
1.4.0 has been released on plugin manager.
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.0

**Comment by MrX-at-GitHub** [comment] 2018-02-17 21:42
@Predelnik 

Thanks, downloaded and set. Just one comment:
Working links are:
ftp://ftp.snt.utwente.nl/pub/software/openoffice/contrib/dictionaries/
and
ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/contrib/dictionaries/

Not working (offline): ftp://gd.tuwien.ac.at/office/openoffice/contrib/dictionaries/

**Comment by Predelnik** [comment] 2018-02-18 11:07
Sure! I will remove non-working ftp from default options in 1.4.1.

**Comment by Predelnik** [comment] 2018-02-19 19:57
I'm closing this since 1.4.0 (and soon 1.4.1 with removed unavailable ftp server) should fix both issues discussed here. Feel free to create new issues in case of any other problems with FTP.

**Closed by Predelnik** 2018-02-19 19:57 UTC
