### ISSUE TITLE
Automatic checking does not work on current tab

### ISSUE THREAD

**Issue by Tharn** [Predelnik/DSpellCheck#179] opened 2019-06-03 08:48 UTC
Using Spellcheck 1.4.12.0 and Notepad++ 7.7.

I have set to 'Spell Check Documents Automatically', set English (US) and German under Multiple Languages and removed all 'Ignore Words'.

The plugin never seems to spell check automatically. Typos remain unchallenged until I set to 'find next' or go into the settings and click 'OK', after which it does a spellcheck pass. The 500ms delay does not seem to be at fault, changing it does nothing.

It also does a spellcheck pass on files opened, or on the current tab when I open a new Notepad++ tab. Just not in a presently-open tab into which text is typed.

**Comment by Predelnik** [comment] 2019-06-03 12:08
Unfortunaltely it is somehow related to version 7.7 of Notepad++, I've checked that it works properly with version 7.6.6. I have to investigate to find out how exactly the plugin was affected.

**Comment by Predelnik** [comment] 2019-06-03 20:54
Here's full story:
* Notepad++ updated its main editing component Scintilla since last release
* Scintilla in some of its updates made breaking change to its structure related to text editing updates
* This structure is exposed to the plugins, thus the plugin using old structure definition may receive incorrect data.

I updated header file with structure definition and will try to release the version which works with Notepad++ 7.7 very soon.

PS It seems to not affect 32-bit versions.

**Comment by heydojo** [comment] 2019-06-05 21:41
Just chiming in to say **me too**.
I downgraded to 7.6 to solve this issue. I only update about twice a year max, so this issue has rocked away my trust in NP++.

Off to VS Code it is for me. And thanks for your work on the spell checker @Predelnik it was working great. I hope you get the issue fixed and quick.

**Comment by Predelnik** [comment] 2019-06-06 05:17
@heydojo 
I already released version with the fix for N++ 7.7: https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.13

It won't be available through official plugin admin until N++ next version will be released though which hopefully will be soon.

**Comment by B3ginnersMind** [comment] 2019-06-12 08:23
N++ and spell check are great. However, this happened the second time to me. I would need a method to know about disruptive API changes in the N++ engine before updating. For now I would recommend to pin the N++ version.

**Comment by deasserted** [comment] 2019-07-12 20:20
I'm running NP++ 32-bit, and I can't get DSpellCheck to install. I assume it is this issue.  If I'm wrong, tell me and I'll start a new thread.

I enjoyed DSpellCheck, but had the same loss of functionality as described by the OP when I upgraded to 7.7.  I tried using the PluginManager to uninstall and re-install DSpellCheck.  NPP acts like it was successful, saying that it is downloading 1.4.9 and asking if I want to restart NPP.  But after the restart, the DSpellCheck menu is NOT visible in the Plugins menu.  Multiple retries were not successful.  I see that it did place the DSpellCheck.dll into my AppData/Roaming/Notepad++/plugins folder.  But somehow it is not registering it upon startup -- perhaps due to the Scintilla changes mentioned above.

I tried downloading the latest (1.4.13) and overwriting the dll.  Then the Plugin Manager still shows DSpellCheck in its Installed tab, but now shows the new version (hooray)... but there is still no menu for it inside the Plugins folder.  Another NP++ restart makes no difference.

THANKS for the great plugin; now if only I can get it back... any ideas?  Is there a NPP file I can manually edit?  Or is this a problem where the 64-bit version was fixed but 32-bit was not, and needs to be?
-- Deasserted

**Comment by Predelnik** [comment] 2019-07-12 20:39
@deasserted

It looks like you are using `Plugin Manager` which seem to no longer work for Notepad++ (newest versions) since it now loads plugins only from folders inside `plugins` folder if I understand it right.
The sad part is that `Plugin Manager` probably will not get updated to support it properly. The correct way to download/update plugins now is through `Plugins->Plugins Admin...`. Unfortunately it updates available versions only with N++ update so to update DSpellCheck to latest `1.4.13` you have to also update N++ to 7.7.1. Hope this helps you with you issue.

**Comment by B3ginnersMind** [comment] 2019-07-12 21:10
What does happen to the installed plugins, if N++ is downgraded? (I solved the problem on 64bit by simply going back to Version 7.6.6.) BTW, "Plugins Admin" still offers to install new plugins but these are neither in the plugins folder not in any other N++ program folder. It appears to be that "Plugins Admin" is able to trigger a download of a plugin but I did not try this it since I am glad that my N++ works again. So perhaps the available plugin and their versions are hard-coded for each version of N++?

This is a little confusing.

**Comment by deasserted** [comment] 2019-07-12 21:50
Predelnik,
Thanks for the tip on the Plugin Admin.  No plugin tool ever appeared for me when I upgraded to NPP 7.7, so I had copied the Plugin Manager from the older version (not realizing it was obsolete).  To get it  to appear, I had to overwrite my old NPP Updater folder and delete my Plugins folder.  Now Plugins Admin appears and I am re-installing my plugins.  

DSpellCheck now appears in the Plugins drop-down folder!  Unfortunately, when I try to install the English US library, I got a frozen downloading progress bar, and then NPP crashes.  I saw that it created a 0-byte file.  So I downloaded the library manually from the address it said it was using, and now DSpellCheck works.  Maybe it had some firewall problem on my side... who knows?  It's working now -- thanks again for your help!
-- Deasserted

**Comment by Predelnik** [comment] 2019-07-12 21:58
@deasserted 

Glad that you were able to fix the problem.

It would be of great help if you will reproduce the crash during downloading, save crash dump through task manager and send it to me by any possible means. If it's not possible then don't worry, I will probably try to look for reason myself. Inability to download might be cause by variety of reasons but crashing is obviously not very nice behavior in such case.

**Comment by deasserted** [comment] 2019-07-16 16:01
@Predelnik,
If I can keep the effort brief, I'll try to provide some crash info. But it's not something I've done before.  I created a dump from Task Manager, but it was >300 MB.  Even if I shrink it, I worry a bit about security in sending such info. What do you suggest I do next?

**Comment by deasserted** [comment] 2019-07-16 16:01
@Predelnik,
If I can keep the effort brief, I'll try to provide some crash info. But it's not something I've done before.  I created a dump from Task Manager, but it was >300 MB.  Even if I shrink it, I worry a bit about security in sending such info. What do you suggest I do next?

**Comment by Predelnik** [comment] 2019-07-16 16:11
@deasserted Well it should only contain memory contents of Notepad++, I guess the only thing you can guarantee is to not have any sensitive information open there at the moment you made dump. Other than that I guess you can trust me to a certain extent I guess.

The other route is, if you know how to use Visual Studio I can send you pdb file and you can tell me call stack and maybe some other needed information.

**Comment by Predelnik** [comment] 2019-07-30 19:18
This error should be fixed by version 1.4.13
@deasserted feel free to send me crash dump and/or create another issue if you want but this error is unrelated to this one anyway so closing.

**Closed by Predelnik** 2019-07-30 19:18 UTC
