### ISSUE TITLE
Idle CPU usage

### ISSUE THREAD

**Issue by sredna** [Predelnik/DSpellCheck#168] opened 2019-02-16 16:57 UTC
DSpellCheck seems to use CPU cycles even when N++ is idle and even worse; when it is not the active window (or even minimized). Perhaps it is possible to disable the timer until the plug-in is notified about changes in the document?

I tried to change DSpellCheck's timer value in the settings dialog to 9999 etc but it seems to have no effect.

To see this CPU usage you can enable the "Cycles Delta" column in Process Explorer. If you remove DSpellCheck then N++ does not use any CPU when idle.

**Comment by Predelnik** [comment] 2019-02-16 18:15
Thanks for reporting, you are right that it is caused by the timer but funnily enough by the timer I used for progress bar updating rather than spell-checking which is accidentaly exists even when progress dialog is not shown. So all in all it should be really easy to fix.

**Comment by Predelnik** [comment] 2019-05-04 08:56
Should be fixed in 1.4.11 version which is now available through `Plugins Admin` system

**Closed by Predelnik** 2019-05-04 08:56 UTC
