### ISSUE TITLE
DSpellCheck makes Notepad++ crash

### ISSUE THREAD

**Issue by donho** [Predelnik/DSpellCheck#146] opened 2018-08-22 13:30 UTC
FYI @Predelnik : 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4752#issuecomment-414968250
and
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4083#issuecomment-414913104

**Comment by donho** [comment] 2018-08-23 10:36
@Predelnik 
It seems the crash has been fixed in v1.4.6 : 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4752#issuecomment-414968250

Is this version stable enough for being included in the new Notepad++ release?

**Comment by donho** [comment] 2018-10-16 07:43
@Predelnik FYI. In case that you are not aware of it, DSpellCheck v1.4.6 has been included in the latest version of Notepad++ (v7.5.9).

**Comment by Predelnik** [comment] 2018-10-16 13:53
Thank you for the heads up! Hopefully it solves the issue.

**Comment by vaxul** [comment] 2018-11-12 14:51
@donho 

> In case that you are not aware of it, DSpellCheck v1.4.6 has been included in the latest version of Notepad++ (v7.5.9).

What does this mean? I haven't found any of this in changelogs. Is it not necessary to install DSpellCheck  separate as plugin?

I have v7.5.9 and after an update oder clean install of DSpellCheck v1.4.7 Notepad++ crashes at every start till I remove the plugin (within the plugin folder).

**Comment by donho** [comment] 2018-11-13 09:35
@vaxul Could you provide the detail of your config here by using Menu "?->Debug Info"?
@Predelnik Have you noticed any crash since 1.4.7 ?

**Comment by vaxul** [comment] 2018-11-13 10:06
@donho 
```
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppExport.dll ComparePlugin.dll HTMLTag_unicode.dll NppEditorConfig.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll 
```

If I try to reinstall the latest Version of DSpellCheck (1.4.7) from the Plugin Manager, Notepad++ crashes with every start without an error message.

I found no logs, to dig into the crash issue.

**Comment by Predelnik** [comment] 2018-11-13 17:21
@vaxul

If it's possible can you please create dump file of Notepad++ after crash happens and send it to me (most likely through Google Drive / Dropbox link since it may not fit to e-mail attachment). Here is how it should be possible in Task Manager:
![image](https://user-images.githubusercontent.com/2133957/48430577-88f1dd00-e767-11e8-9c32-c410fcfc3309.png)

The other thing which may be useful is contents of your plugin settings file located in `%appdata%\Notepad++\plugins\config\DSpellCheck.ini`.

@donho
No crash on start was specifically fixed in 1.4.7 and hopefully nothing crash inducing was added either. But I would definetily would like to fix it asap in next version.

**Comment by Branwyn** [comment] 2018-11-14 07:38
confirm it start crashing after installing NPP++ v. 7.6. (plugin version 1.4.7)

in my case - understood crash was caused by setting (from previous installation) plugin to check multiple languages (Aspell, any language more then one selected, same time - each language spell checking is working fine separately).

found this initially by switching off each plugin, then by replacing content of my INI from previous version installed:
~~~
[SpellCheck]
Aspell_Multiple_Languages=en|en_US|ru|uk
Aspell_Language=<MULTIPLE>
Hunspell_Language=en_US
Library=0
~~~

with freshly installed INI:

~~~
[SpellCheck]
Autocheck=0
Hunspell_Language=en_US
~~~

and then by experimenting with number of languages to be checked.

**Comment by vaxul** [comment] 2018-11-14 08:01
After removing the existing `%appdata%\Notepad++\plugins\config\DSpellCheck.ini.` Notepad++ doesn't crashing after installing  DSpellCheck.

The content of the INI before:
```
[SpellCheck]
Aspell_Multiple_Languages=de|de_DE|en|en_GB|en_GB-w-accents
Aspell_Language=<MULTIPLE>
Library=0
```

After redefine the config the INIs content is:
```
[SpellCheck]
Hunspell_Multiple_Languages=en_GB|en_US|de_DE_frami
Hunspell_Language=<MULTIPLE>
```

Switching the INI back to the faulty one lets NPP+ crashing again.

**Comment by Predelnik** [comment] 2018-11-14 08:44
Ok so it seems this crash is truly caused by version 1.4.7 changes. I even noticed the possibility of it but deemed it to be not serious.
Can you please check that the version below no longer crashes with your original settings file?
https://ci.appveyor.com/api/buildjobs/2u9whys9s0vaagwm/artifacts/DSpellCheck.dll

If it does not I will try to release a version with the fix as soon as possible.

Note that this crash has nothing to do with issues linked in the topic and affects only version 1.4.7.

**Comment by Branwyn** [comment] 2018-11-14 09:47
no crashes with DLL as per provided above link (albeit difference in size of approx 1 mb)

**Comment by vaxul** [comment] 2018-11-14 09:56
I testet the x86 Version https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.6 with the old config it NPP++ doesn't crash with it.

> https://ci.appveyor.com/api/buildjobs/2u9whys9s0vaagwm/artifacts/DSpellCheck.dll

This one does also work.

**Comment by Predelnik** [comment] 2018-11-14 09:58
Ok, thank you very much for testing! I will try to officially release new version with the fix today or tomorrow.

> albeit difference in size of approx 1 mb

Oh don't worry too much about it, official release will probably have the same size. It's just some difference in appveyor build script (appveyor is an utility for quickly checking that plugin builds) from normal build I do. It would be interesting to find out what's different but it isn't critical in any way.

**Comment by Predelnik** [comment] 2018-11-20 21:54
1.4.8 is now available through plugin manager, so second (aspell users only) crash discussed in this issue is fixed, closing.

**Closed by Predelnik** 2018-11-20 21:54 UTC

**Comment by Predelnik** [comment] 2018-11-21 12:51
@donho Sure! I will look into that, probably need a bit of time to figure out how to test things locally.
