### ISSUE TITLE
Notepad++'s Plugin Manager fails to install

### ISSUE THREAD

**Issue by AndovaBegarin** [Predelnik/DSpellCheck#80] opened 2016-06-28 21:08 UTC
Trying to install this from Notepad++'s Plugin Manager fails (v6.9.1). Not certain why. Manually downloading:

```
https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.2/DSpellCheck.zip
```

and extracting the DLL seems to work. But I get the error:

```
Aspell Status: No dictionaries
```

Even though:

```
C:\Program Files (x86)\Aspell\bin\aspell-15.dll
```

exists as I did install Aspell.

(I must be doing something wrong...)

**Comment by Predelnik** [comment] 2016-06-28 21:29
Dictionaries for Aspell for windows are separate installers. You can
download them there http://aspell.net/win32/
It should be easier to use Hunspell though.

Best regards, Sergey Semushin

**Comment by AndovaBegarin** [comment] 2016-06-28 21:34
Thank you very much. Turns out I had done something wrong: Installed the Aspell program but not the dictionary. Doing the latter fixed it. (Still, Plugin Manager does not install DSpellCheck. Works fine with manual install.)

**Comment by chcg** [comment] 2017-09-14 15:40
@AndovaBegarin Do you still have a problem in installing DSpellCheck with PluginManager https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9 ?

**Comment by Predelnik** [comment] 2017-10-29 13:57
I had some trouble with installing on Windows XP machine. Maybe that's the case? 

For me it was probably caused by the fact that maybe Windows XP needs something additional to support downloading through https. But almost any plugin now is on https so probably it should be resolved on a client side.

**Comment by chcg** [comment] 2017-10-30 06:03
See https://github.com/bruderstein/nppPluginManager/issues/40. PM depends on the windows ssl/tls implementation and that one is not updated to support TLS 1.1, what causes issues with current https servers enforcing the usage of the more secure protocols.

**Comment by Predelnik** [comment] 2017-10-30 18:28
Ok I think it's sad but it's most likely Plugin Manager/Windows XP interaction problem, so I'm closing this for now, feel free to reopen if my guess was incorrect.

@chcg thanks for the link!

**Closed by Predelnik** 2017-10-30 18:28 UTC
