### ISSUE TITLE
crash when use the develop npp++ from 29.01.2020

### ISSUE THREAD

**Issue by KlausiD** [Predelnik/DSpellCheck#280] opened 2022-01-29 16:56 UTC
the plugin is crash when use the develop npp++!
npp++ has change the interface 
see:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104#issuecomment-1024934304
and
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1024048200

**Comment by pryrt** [comment] 2022-01-31 22:18
FYI: per [this](https://community.notepad-plus-plus.org/post/73539) and [this](https://community.notepad-plus-plus.org/topic/22469/notepad-v8-2-2-release-candidate-5), with v8.2.2 RC5, the NPP installer is actively disabling DSpellCheck for anyone who has it already installed, and that might mean he's also removed it from Plugins Admin (though I'm not sure) -- which means that users are going to have to start fighting against Don unless an update-with-patch is released ASAP (preferably before v8.2.2 is fully released)

**Comment by donho** [comment] 2022-02-01 14:13
@Predelnik 
Here's the complement info:

Due to the support 2GB files opening in [Notepad++ v8.2.2 x64 build](https://community.notepad-plus-plus.org/topic/22469/notepad-v8-2-2-release-candidate-5), the header **Sci_Position.h** in Notepad++ has been modified for adapting this need.
This change has caused the instability of DSpellCheck.

How to reproduce crash:
1. Install DSpellCheck Plugin in Notepad++ v8.2.2 x64 build
2. Restart Notepad++ -> Notepad++ crash

The solution is quite simple - just replace **Sci_Position.h** by [the new one](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Sci_Position.h) (or just replace ~~`typedef long Sci_PositionCR;`~~ by `typedef intptr_t Sci_PositionCR;` in **Sci_Position.h** of your project), then recompile DSpellCheck.
ref:
https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

Could you please update DSpellCheck ASAP (and also PluginList) so I could work on installation (NSIS) script to remove only the old versions, but keep the new fixed version, just as how [installer deals with NppSaveAsAdmin plugin](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nsisInclude/mainSectionFuncs.nsh#L224) currently.

Sorry for the inconvenience and thank you in advance for your help.

**Closed** 2022-02-03 09:28 UTC

**Comment by donho** [comment] 2022-02-03 16:07
@Predelnik 
Please do a PR on Plugin list for your new release.
I can include it (modify NSIS and include the newest PluginList) if your release and PR on Plugin list is on time (ie. in 4 hours). Otherwise no problem - Notepad++ will be released more frequently with **updated plugin list** to ensure its usability.

Thank you for your help!

**Comment by Predelnik** [comment] 2022-02-03 20:56
Don't know if I was in time or not, but here it is:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.23

https://github.com/notepad-plus-plus/nppPluginList/pull/405

Unfortunately I'm sick right now, so my response time is a bit delayed, sorry.

**Comment by Yaron10** [comment] 2022-02-03 22:04
@Predelnik,

👍 
Thank you for your work.

I hope you get better soon.

**Comment by donho** [comment] 2022-02-03 22:46
It's right on time! I'm doing the release.
Thank you @Predelnik for your help, and hope you getting better soon.
