### ISSUE TITLE
plugin causes crash of notepad++ in doc switcher

### ISSUE THREAD

**Issue by seligam** [Predelnik/DSpellCheck#126] opened 2018-01-31 12:38 UTC
notepad++ always crashes when i rightclick on name column of doc switcher with DSpellCheck.dll enabled. no problem when plugin is disabled

### Steps to Reproduce the Issue
1.  open notepad++
2.  configure it that doc switcher is visible
3.  open some files
3.  rightclick on name column

### Expected Behavior
open menu

### Actual Behavior
application crashed

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll

DSpellCheck.dll is 1.3.5.0

**Comment by Predelnik** [comment] 2018-01-31 20:38
Sadly can't reproduce with just that:
![image](https://user-images.githubusercontent.com/2133957/35646134-45aa569e-06df-11e8-8917-478a879e4350.png)
Maybe some other condition also needs to be fullfilled. But if you would just send me crash dump I would probably have enough to work with:
![image](https://user-images.githubusercontent.com/2133957/35646283-b8b7bd84-06df-11e8-85f7-3cbd1751dd79.png)

**Comment by seligam** [comment] 2018-02-01 07:36
To make it crash then in name colum rightclick not on name of file but on name of column 
![bugreport](https://user-images.githubusercontent.com/13021716/35666597-fda1d8b2-072a-11e8-9907-e37e239ac50d.png)

**Comment by seligam** [comment] 2018-02-01 07:43
it doesn't want to upload dump here (56MB compressed)

**Comment by Predelnik** [comment] 2018-02-01 08:22
Ok I was able to reproduce it on other machine but then I moved DSpellCheck to disabled and it still crashes. Are you sure it is DSpellCheck related after all?
On my original machine it doesn't crash but doesn't display any menu on header either.

**Comment by seligam** [comment] 2018-02-01 08:44
I removed all plugin dlls from c:\Program Files\Notepad++\plugins\ and there was no crash. on right click context menu is opened, the same as I would rightclick on name of file

then i return only DSpellCheck.dll and restart notepad++. on rightclick it crashes

then i remove DSpellCheck.dll and return all other plugins i have, restart notepad++. on rightclick there is no problem again

just a hint, I am using 64bit version of notepad++ and plugin, it might behave differently then 32bit version?

**Comment by Predelnik** [comment] 2018-02-01 10:42
Yes on x86 I can't reproduce it with or without DSpellCheck but don't have any context menu either. On x64 it crashes with or without. And have version 7.5.4 on both.

Well then your crash dump could still prove useful. Try send it to me directly to predelnik@gmail.com or through Google Drive/OneDrive/DropBox.

**Comment by Predelnik** [comment] 2018-02-01 21:06
Ok first of all thank you for crash dump sadly it wasn't of much use because missing DSpellCheck.dll in call stack. However I was able to reproduce it on my machine (when it depends on DSpellCheck just like in your case but doesn't have it in call stack too). It seems like it doesn't happen with 1.4.0 version. So it would be really great if you would download and confirm that it works (it's beta but I hope to release it soon): https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.0-beta2

Next follows a little rant:
I just don't understand how can one single thing behave so differently on different systems and with diferent plugins within exactly the same N++ version. Even with debug version of DSpellCheck 1.3.5 it does not crash. I'm gonna build debug version of Notepad++ and try to get to the bottom of it this weekend (only if it doesn't magically disappear when I will use VS2017 for building npp or something like that)

**Comment by seligam** [comment] 2018-02-02 14:31
1.4.0 beta doesn't crash for me. You have fixed it in advance :)

and about your rant, I have some years of experience in C/C++ and I would bet that problem is in something initialized/cleared in debug mode but left uninitialized in release mode. My guess would be that when you rightclick on rows with file name something gets set to information from this row. if you rightclick elsewhere then it doesn't, but some structure may not be cleared properly. And maybe you need it. In that case problem may be in notepad++ itself (not clearing something). But of course I may be completely wrong, I didn't bothered to look into sources at all

**Comment by donho** [comment] 2018-02-17 11:38
Any progress about this issue @Predelnik ?

**Comment by Predelnik** [comment] 2018-02-17 19:51
Well it doesn't happen with 1.4.0 which I already released on plugin manager.
Also as I checked it doens't happen with debug version of Notepad++ so the cause is unknown.

**Comment by Predelnik** [comment] 2018-02-19 19:56
I'm closing this because it was fixed (accidentally?) in 1.4.0 which is now available on plugin manager. Underlying cause in Notepad++ may be interesting to determine but doesn't look that easy sadly.

**Closed by Predelnik** 2018-02-19 19:56 UTC
