### ISSUE TITLE
Crash when pressing Apply in settings dialog

### ISSUE THREAD

**Issue by georgthegreat** [Predelnik/DSpellCheck#110] opened 2017-11-16 18:46 UTC
That's all I know.
I have my settings stored in cloud.
DSpellCheck crashes when I'm trying to save my settings.
I'm using x64-bit Notepad++ = 7.5.1 and DSpellCheck 1.3.2 (tried some previous version, but the crash was the same).

That's it. Unfortunately, I do not know how to send you a core dump / backtrace.

I don't a debugger on my laptop.

**Comment by Predelnik** [comment] 2017-11-17 07:39
So I've tried it and it looks like for me N++ saves only its own settings on the cloud (not for plugins) so it shouldn't affect plugin workflow. Do you also use "Don't use %APPDATA%" in N++ setup?
Also please elaborate what do you mean by "save settings" is it when you change something in N++ preferences or when press apply in DSpellCheck settings?

Well as far as I remember for core dump you don't need debugger but let's leave it as the last step, maybe I'll be able to reproduce it myself afterall.

**Comment by georgthegreat** [comment] 2017-11-17 07:49
I also have my Hunspell path set to the path within the cloud
($PATH_TO_NPP_CONFIGS/Hunspell, actually). Both are set as Current User and
the General path for dictionaries.
I have "Unified user dictionary" set to true.

I've used default flags during NPP installation. AFAIR, it does not have
"Don't use appdata" set by default.

**Comment by georgthegreat** [comment] 2017-11-17 07:50
I've also checked if this setting will work on my other laptop — it works
properly.
It looks like something is wrong with my installation of NPP, but I can not
actually say what.

**Comment by georgthegreat** [comment] 2017-11-17 07:56
I'll try to reinstall NPP from scratch.
Can you start saving setting to the cloud somehow?

**Comment by Predelnik** [comment] 2017-11-17 07:57
Well you may try to create dump via context menu in task manager, maybe that would help. Do you have that option?
![image](https://user-images.githubusercontent.com/2133957/32936536-b591885a-cb85-11e7-9b65-4da85b2f7a97.png)

As for can plugin save settings to the cloud - maybe with "don't use %appdata%" they would I haven't tried it though.

**Comment by georgthegreat** [comment] 2017-11-17 20:54
Ok, I have reinstalled NPP from scratch and I've added option "Don't use appdata" (i. e. I have local file 
The crash is still here.

I have created a dump with Process Hacker, you can find it here: https://yadi.sk/d/-2Ir_EH-3PoM3T

**Comment by Predelnik** [comment] 2017-11-18 08:17
Sorry, can you also get dump for this version for me?
https://drive.google.com/uc?export=download&id=0B_fsSThBdq2mOE5oN3poczRhX3c
I figured out that I can't do much without debug info especially since Visual Studio version has changed since I deployed and code seems really different. Possibly I will attach debug info on all next distributions to simplify an investigation of cases like this.

**Comment by georgthegreat** [comment] 2017-11-18 09:19
Here you go: https://yadi.sk/d/-2Ir_EH-3PoM3T

**Comment by Predelnik** [comment] 2017-11-18 15:38
Ok now it's easy to see what's happening 
It tries to open file "C:\\Users\\georg\\AppData\\Roaming\\Notepad++\\plugins\\Config\\DSpellCheck.ini" for writing and fails and I don't have any adequate message box/check in case of failure. Apparently doing `fclose (nullptr)` leads to crash. Can you create this file manually? Perhaps some directory in the path is missing (like the last Config)?
 
(I'm adding error check and message box to my to-do list already but just want to figure out what is the problem in your spefic case)

**Comment by georgthegreat** [comment] 2017-11-19 14:40
Ok, I've created this folder manually and now it works pretty well.

I assume you can close this issue now, but, please, consider supporting
cloud based configuration which is available in NPP for quite some time now.

**Comment by Predelnik** [comment] 2017-11-19 15:34
Hmm so as it turns out while `config` directory will be automatically created by DSpellCheck, `plugins` directory will not and this is another thing which I should fix.

As for cloud based, the problem is that I have to use directory returned by Notepad++ itself (via message NPPM_GETPLUGINSCONFIGDIR) and I don't see any other similar thing in its interface. Do you know any other plugins that support cloud based configuration perhaps?

**Comment by georgthegreat** [comment] 2017-11-19 15:42
No, I do not use any plugins except for DSpellCheck.

**Comment by Predelnik** [comment] 2017-11-30 19:52
@SinghRajenM 
Do you use v1.3.2 or v1.3.3? This issue was clearly unrelated to hunspell dictionaries path (due to crash dump and all), so you better create another one if it is related.

From what I see from quick lookup. `FindFirstFile/FindNextFile` find all the directories on Homedrive for mask "\*.*" (I have no idea why) since I do scanning recursively it goes through a lot of directories but never crashes for me. I could add check on empty path but I'm not sure if that's really needed.

**Comment by Predelnik** [comment] 2017-12-09 20:55
I'm closing this since the changes were added to version 1.3.3 which is available through plugin manager.

@SinghRajenM If you still getting crash with 1.3.3 in scenario you described (not just long wait) please don't hesitate to open another issue.

**Closed by Predelnik** 2017-12-09 20:55 UTC
