### ISSUE TITLE
Mistakes  v1.4.0 alpha3

### ISSUE THREAD

**Issue by DmFedorov** [Predelnik/DSpellCheck#120] opened 2018-01-05 10:02 UTC
in v1.4.0 alpha3 (I see that you are preparing a version of alpha4)
1) if Settings | Advanced = Split Words by the Following Delimiters:
then..
- Words are not separated by a space. The space must be entered in this list, then the words are separated. 
- Words after which the line ends immediately are underlined.

2) checkbox in section Ignore Words "Having _" does not seem to work (works if symbol _ is in list "Split Words by Non-Alphabetic Characters Except"). Maybe some others do not work too.

**Comment by Predelnik** [comment] 2018-01-06 18:30
1st should be fixed in alpha4:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.0-alpha4
As for 2nd it works as intended but I'm not sure if undescore should be part of exclusions by default.

**Comment by SinghRajenM** [comment] 2018-01-07 08:15
> As for 2nd it works as intended but I'm not sure if undescore should be part of exclusions by default.

No it is not working. Check/uncheck ("Having _" ) does not have any effect.

![image](https://user-images.githubusercontent.com/14791461/34647735-f9e25ae0-f3b0-11e7-832a-e52a85922db4.png)

**Comment by Predelnik** [comment] 2018-01-07 09:18
It should not have an effect if word does not contain `_`. In your case word is `Aadhar` it doesn't contain  `_` how it supposed to work in your opinion?

**Comment by DmFedorov** [comment] 2018-01-07 10:03
OK. Then this misunderstanding.
Probably needed to translate the name of  section "Ignore Words" as approximately  "Words that ignored after splitting"

**Comment by SinghRajenM** [comment] 2018-01-07 14:01
> In your case word is Aadhar it doesn't contain _ how it supposed to work in your opinion?

IMHO, word "Aadhar_Card" or "po_wer" should be ignored if "Having _" is checked similar to "Containing Numbers".

![image](https://user-images.githubusercontent.com/14791461/34649998-5bbe6384-f3df-11e7-9cc4-449876297768.png)

**Comment by Predelnik** [comment] 2018-01-07 16:13
> IMHO, word "Aadhar_Card" or "po_wer" should be ignored if "Having _" is checked similar to "Containing Numbers". And if the "Having _" is not checked, then treat them as separate words (e.g. Aadhar, Card, po, wer etc.).

For me personally that sounds too complicated to make this option affect word splitting. The easier solution for me is just add it to the list of exclusions. Then it will "work" in default case just as it was  "working" with default explicitly specified delimiters and "not working" when _ is selected as a delimiter. 

In reality I don't think that option is even that useful or important anymore.

**Comment by SinghRajenM** [comment] 2018-01-07 17:07
> The easier solution for me is just add it to the list of exclusions. 

As this option is default checked, I feel this is good to add it to the exclusion list. When use uncheck, this can be removed from exclusion list. However, most of the time users deal with default setting, so it should not be an issue.

![image](https://user-images.githubusercontent.com/14791461/34651781-008e31bc-f3fb-11e7-9cc3-8f71d9cca3cc.png)

I'm not much familiar with dspellcheck codebase, but I will try to debug and see if I can contribute towards this issue.

> In reality I don't think that option is even that useful or important anymore.

If so, then I feel this option be removed from UI at all to avoid confusion. If user wants, he/she can add required delimiter(s) to exclusion list.

**Comment by Predelnik** [comment] 2018-01-07 18:02
> I'm not much familiar with dspellcheck codebase, but I will try to debug and see if I can contribute towards this issue.
This is not issue with codebase but with my vision how these things should be handled. Making checkbox affect delimiters in my opinion creates much more confusion. Also it removes the option to add/ignore words containing underscore manually. But my biggest gripe with all of it is that nothing is changed except the set of default delimiters which now happen to contain underscore.

**Comment by Predelnik** [comment] 2018-01-07 19:17
I added underscore to default exclusions in master. Hopefully it resolves this issue.

**Closed** 2018-01-14 20:24 UTC
