### ISSUE TITLE
DSpellCheck 1.4.13 on Notepad++ 7.7 - Alt-N and Alt-B hotkeys no longer work

### ISSUE THREAD

**Issue by Tabbious** [Predelnik/DSpellCheck#181] opened 2019-06-23 13:01 UTC
Just updated to version 1.4.13 with Notepad++ 7.7 and can no longer "Find Next Misspelling" using the "Alt-N" hotkey.  Same goes for "Find Previous Misspelling" using the Alt-B hotkey.  These hotkeys are not listed in the DSpellCheck plugin pull down menu.  Will these hotkeys no longer be supported?

**Comment by Predelnik** [comment] 2019-06-23 14:38
Quoting the change from v1.4.7:
> Remove hotkeys enabled by default because they collide with useful actions in some localizations (#150). Please configure them yourself through Settings->Shortcut Mapper if you need them.

Please configure them by yourself if you need them. Unfortunately these weren't good defaults suitable for all and `Alt + ...` hotkeys in general are not very good because they could be used for menu navigation.

**Comment by Predelnik** [comment] 2019-07-30 19:21
Closing this is an expected behavior now, customizing hotkeys for plugin should be relatively easy but default ones were resulting in too many conflicts.

**Closed by Predelnik** 2019-07-30 19:21 UTC
