### ISSUE TITLE
DSC does not Automaticly Check Spelling even when the Option is Checked with the Native Library in Win 10 on NPP 7.8.9.

### ISSUE THREAD

**Issue by MadokaAyukawa** [Predelnik/DSpellCheck#222] opened 2020-09-07 18:30 UTC
After upgrading, the document will not be automatically spell checked with 1.4.16 and 17 with the Native Win 10 library in NPP 7.8.9. I can turn the option off and on, and it will check the displayed portion of the document. If I scroll down, the misspellings will not be marked again. It's possible that DSC has spellchecked the document, and it's a display issue with NPP.

It does seem somewhat random as sometimes it seems to work normally, but this non-checking has happened multiple times now for me to post an issue.

Edit: It also seems to have the same issue with the Hunspell library.

Edit2: If I type something in the section of the document that's not showing any spelling errors, then DSC will display the errors.

**Comment by Predelnik** [comment] 2020-09-11 11:45
Has this problem appeared only with the latest versions or has it always been the case?
Currently seems to work fine for me but I have only 7.8.7 N++

**Comment by MadokaAyukawa** [comment] 2020-09-11 16:45
This is new with 7.8.9. It seems to work with 7.8.8. When I scroll in 7.8.8, I can see DSC marking new misspellings. 7.8.9 seems to be stopping DSC from refreshing the screen until I type something as far as I can tell.

**Comment by Predelnik** [comment] 2020-09-12 16:06
I've installed 7.8.9, seems to work fine for me, do you maybe have any specific file where it can be reproduced?
And maybe just in case post contents of `%appdata%\Notepad++\plugins\config\DSpellCheck.ini` and list other plugins you have installed

**Comment by MadokaAyukawa** [comment] 2020-09-12 16:09
```

[SpellCheck]
Hunspell_Multiple_Languages=en_GB|en_US
Hunspell_Language=<MULTIPLE>
Native_Speller_Multiple_Languages=en-CA|en-US
Native_Speller_Language=<MULTIPLE>
Underline_Style=0
Ignore_Have_Capital=0
Ignore_All_Capital=0
United_User_Dictionary(Hunspell)=1
Library=2
```
It will do it on most files, it seems. I would have to re-install 7.8.9 to check as I've been using 7.8.8.

**Comment by MadokaAyukawa** [comment] 2020-09-15 00:37
I re-installed 7.8.9 again. It can happen to any text file. It's somewhat random as the same file will work fine one time and not another time. I did notice when NPP/DSC is not displaying the misspellings, just clicking on another tab and back will display the misspellings in the visible section of the file. The rest of the file will not show the misspellings so one needs to repeat that tab clicking procedure. Going back to 7.8.8 for now.

**Comment by Predelnik** [comment] 2020-09-15 09:37
I already found 7.8.9 problem with "Suggestions button" which is annoyingly hard to fix (and I can't ask N++ to fix it either it seems), it would be really sad if there's another issue like it :(

**Comment by Truthowl** [comment] 2020-09-16 16:03
I'm having the same issue except I'm using npp 7.8.8. Thank you @MadokaAyukawa for the tip of switching tabs and then back to show misspellings. That works for me too. I'm using Windows 10. I just noticed this today. I don't use npp very often so I don't know how long the issue has been happening.

**Comment by Predelnik** [comment] 2020-09-19 12:22
Still can't reproduce it on my side unfortunately, if you figure anything specific for when it happens or about your setup please share it. Also you may try `Enable Debugging Log` from `Additional Options` in case this happens, then scroll a bit, then `Open Debug Log`, don't forget to disable it after though, it may provide marginal benefit in figuring out what's going on.

**Comment by MadokaAyukawa** [comment] 2020-09-26 20:11
I found a file that does this constantly. Could it be that big block of text in the [Font] section messing up DSC?

[Okane no Kireme ga Koi no Hajimari S01E01 1080p WEB-DL AAC H.264-NSBC.ass.zip](https://github.com/Predelnik/DSpellCheck/files/5287269/Okane.no.Kireme.ga.Koi.no.Hajimari.S01E01.1080p.WEB-DL.AAC.H.264-NSBC.ass.zip)

**Comment by Predelnik** [comment] 2020-09-27 09:01
@MadokaAyukawa Thank you for sending a specific file, can't reproduce it for now after trying some stuff. Just wanted to make sure - you are not using any UDL for `.ass` files?

**Comment by MadokaAyukawa** [comment] 2020-09-27 15:59
No I am not. I have not added any UDLs in NPP++.

**Comment by Predelnik** [comment] 2020-10-03 17:53
Seems like I was able to reproduce it once but was not in debug at that time unfortunately and after restarting can't reproduce anymore 😢

**Comment by MadokaAyukawa** [comment] 2020-10-03 17:56
Yeah it's like that, seems random. It also does it with the new 7.9.

**Comment by Predelnik** [comment] 2020-10-04 09:08
Finally solved!
Due to poorly written code, scroll and fast typing after that is breaking rechecking mechanism for scroll, will try to fix asap.

**Comment by MadokaAyukawa** [comment] 2020-10-04 18:46
Thank you so much for looking into this!

**Comment by MadokaAyukawa** [comment] 2020-10-07 19:51
1.4.18 didn't fix this issue with 7.9

**Comment by Predelnik** [comment] 2020-10-08 06:36
I can't reproduce it the same way at least which was very easy before, very strange. Maybe I'll have to look into it again for next version then(

**Comment by Predelnik** [comment] 2020-10-16 04:45
At least some cases of this should be fixed by 1.4.18, if it still happens it would be great to find specific scenarios for reproducing.

**Comment by MadokaAyukawa** [comment] 2020-10-25 07:31
The new release (19) does this right away on the first run of NPP. I closed, and reopened and it did it again. 

I have been trying out prior version to see if I can find one that doesn't do it. I'm testing 14 right now. 15–19 will all stop spell checking on it's own.

**Comment by Predelnik** [comment] 2020-10-25 18:57
@MadokaAyukawa 
Can you check if this version helps in your case?
x64: https://ci.appveyor.com/project/Predelnik/dspellcheck/builds/35944924/job/6osmew4lux84hqk5/artifacts
x86: https://ci.appveyor.com/project/Predelnik/dspellcheck/builds/35944924/job/lp477xen1she2wqj/artifacts
I cannot reproduce it but there might be some rough parts in rechecking which I'm trying to fix (and need to do more probably). If it does I will likely include this in 1.4.19.

**Comment by MadokaAyukawa** [comment] 2020-10-25 19:07
I have downloaded it and will test it. Good news is that it does spellcheck when I first open NPP. I'll keep checking as I still have not determined what conditions will cause the non-checking to start and things seem random still.

I have been testing 14 for about a week, and so far it has worked so far. Will report back.

**Comment by MadokaAyukawa** [comment] 2020-10-25 21:23
Here's an interesting development. I lowercase i is marked as misspelled under line 3, but not in the later ones in the beginning of the line, but is marked at the end of the line. Further down in the file, it is marked both beginning and end.

![Untitled](https://user-images.githubusercontent.com/44476321/97119474-ad81be00-16cd-11eb-9a8c-cba4fd38b3be.jpg)

**Comment by Predelnik** [comment] 2020-10-26 18:51
@MadokaAyukawa That I can reproduce and luckily it's a separate issue with native speller, currently it does combine all the words to be checked in a single space separated line before calling an API due to it being much faster, but spell-checking API seems to apply some positioning logic to frequent words such as "i". Combining does seem to be less of importance now as updates are spaced out by timer but still gives some benefit, not sure if there would be some easy fix without disabling it but I will look into that.

Anyway, I found another issue with timer initialization I will post a link to binary here soon. And now I'm certainly going to add these changes to 1.4.19.

**Comment by MadokaAyukawa** [comment] 2020-10-26 20:19
I got the 32-bit version when clicking on the 64-bit link and NPP had a fit. :)

**Comment by Predelnik** [comment] 2020-10-27 03:57
@MadokaAyukawa Sorry for this, fixed the link

**Comment by MadokaAyukawa** [comment] 2020-10-27 04:20
No worries. Testing the new one now.

**Comment by MadokaAyukawa** [comment] 2020-11-11 02:06
I have started testing .20. The good news is that the version that I got from the above link worked fine and did not demonstrate the non-spelling behavior.

**Comment by MadokaAyukawa** [comment] 2020-12-16 18:59
I've been testing .20 or over a month now, and so far DSC has worked as expected ever time.

**Comment by Predelnik** [comment] 2021-01-03 14:47
Very good then, I guess this issue can be finally closed now, seems like all the problems were due to mishandling of timers by me.

**Closed by Predelnik** 2021-01-03 14:47 UTC
Labels: needs-more-info
