### ISSUE TITLE
Can't  install dictionary

### ISSUE THREAD

**Issue by marko-pi** [Predelnik/DSpellCheck#94] opened 2017-09-19 07:58 UTC
I am using DSpellCheck for Notepad++ x64.  Notepad++ starts in administrator mode.

When I want to download dictionaries, I get error "Can't create directory C:" or "Can't create directory .", depending if I choose "Install for all users" or not.

It is working fine since I *manually* created directory %NOTEPAD++_DIR%\plugins\config\Hunspell.

**Comment by Predelnik** [comment] 2017-09-19 20:53
Thanks! I fixed that and will close when new version will be released.

**Closed** 2017-09-19 21:14 UTC

**Comment by marko-pi** [comment] 2017-09-19 22:27
Thanks for the plugin and fast reaction.

**Comment by abdekker** [comment] 2024-01-03 22:00
This issue appears to be back on a fresh installation of v8.6 x64 on Windows 10. Kept getting the following error when I tried to download the "English (United Kingdom)" dictionary:
    Can't create folder .plugins\config\Hunspell.

Manually creating the "Hunspell" folder in C:\Program Files\Notepad++\plugins\config made the error disappear, only to show a different error about dictionaries not being downloaded because "they could not be saved.

Resolved by closing NPP and re-launching in Administrator mode.

**Comment by Teufelauto** [comment] 2024-10-04 00:07
Thank you, @abdekker. 'Re-launching in Administrator mode' makes the plugin function as intended for the initial dictionary download.

v8.7 x64 on Win10

**Comment by Dalef1949** [comment] 2026-03-13 21:45
I would also like to thank you for this explanation. It did the trick for me too.
