### ISSUE TITLE
Running DSpellCheck Without Admin

### ISSUE THREAD

**Issue by JCampione** [Predelnik/DSpellCheck#83] opened 2016-07-25 04:24 UTC
Hi all, 

Running fresh installs of Win10 and Notepad++ v6.9.2. 

I'm having an issue where if I run Notepad++ without admin DSpellCheck doesn't work correctly.

I find that almost every word is underlined but only the "ignore" and "add" options are available for selection.  But if I run as admin it works fine. 

The accounts I'm using are specifically not admin for security reasons and I have users that use Notepad++ for spellcheck because it's lighter than MSWord, and the PCs are offline. 

Is there any particular reason why Notepad++ would require admin? 

Thanks.

**Comment by jsberg-bnl** [comment] 2016-11-30 16:58
The problem here is the dictionaries that are downloaded to the all users folder have a security descriptor set on them which restricts permissions pretty severely and disables inheritance. It is easily fixed using icacls /reset on the files, which just removes the security descriptor and lets the files inherit permissions from the parent (which is usually the right thing to do on Windows). I scanned through the code and am a bit unclear as to why this is occurring, but my suspicion lies with the use of _topen in DownloadDicsDlg.cpp. I would suggest trying CreateFile instead, and similarly replacing _write and _close with WriteFile and CloseFile respectively. This is just a wild guess, haven't tested this. Also, note that according to the MS docs, _topen should be called with a third argument when _O_CREAT is present.

**Comment by Predelnik** [comment] 2017-10-12 19:08
Can't reproduce for now. I try the following:
1. Run N++ in administrator mode
2. Download a dictionary.
3. Open N++ in normal mode, dictionary seems to work ok.

I thought it was fixed due to newer version of Visual Studio I'm compiling with, but I also checked some a bit older versions. It'd be nice to know which version of plugin had that bug but I understand that since I'm responding quite late this may not be an option.

**Comment by Predelnik** [comment] 2017-10-12 19:15
Sorry I'm being stupid, I just created non-admin account and it's broken. I will definitely fix that.

**Comment by Predelnik** [comment] 2017-10-14 06:54
Will be fixed in 1.4.0

So for those interested it happens because I move files from temporary directory as a final step which doesn't inherit permissions according to https://blogs.msdn.microsoft.com/oldnewthing/20060824-16/?p=29973/

Maybe it would be easier to just avoid moving files at all but for now I just added the code for resetting those permissions to correct ones.

**Comment by Predelnik** [comment] 2018-02-19 19:44
1.4.0 version with this fix is now available through plugin manager, closing this issue.

**Closed by Predelnik** 2018-02-19 19:44 UTC
